apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tile38-server-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: tile38-server
  endpoints:
  - port: 3000
    path: /metrics